name: black
on: push
jobs:
  black:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v1
        with:
          python-version: 3.11
      - run: |
          python -m pip install --upgrade pip
          pip install poetry
          poetry install
          poetry add black
      - run: |
          poetry run black project_first/
